name: Backend CI — Build & Push (SHA tags)

on:
  push:
    branches: ["testing"]
    paths:
      - "backend/**"
      - ".github/workflows/backend_ci.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  ACR_NAME: ${{ secrets.ACR_NAME }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ["product_service", "order_service","customer_service"] 

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: ACR login
        run: az acr login --name $ACR_NAME

      - name: Build & push image (SHA tag)
        uses: docker/build-push-action@v6
        with:
          context: ./backend/${{ matrix.service }}
          push: true
          tags: ${{ env.ACR_LOGIN_SERVER }}/${{ matrix.service }}:${{ github.sha }}
