version: "3.9"

services:
  # ===== DBs =====
  product_db:
    image: postgres:15-alpine
    container_name: product_db_container
    restart: always
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - product_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d products"]
      interval: 5s
      timeout: 5s
      retries: 10

  order_db:
    image: postgres:15-alpine
    container_name: order_db_container
    restart: always
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - order_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d orders"]
      interval: 5s
      timeout: 5s
      retries: 10

  # ===== Backends =====
  product_service:
    build:
      context: ./backend/product_service
      dockerfile: Dockerfile
    image: local_product_service:latest
    container_name: product_api_container
    restart: unless-stopped
    depends_on:
      product_db:
        condition: service_healthy
    environment:
      POSTGRES_HOST: product_db
      POSTGRES_DB: products
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      ENV: local
    volumes:
      - ./backend/product_service/app:/code/app
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  order_service:
    build:
      context: ./backend/order_service
      dockerfile: Dockerfile
    image: local_order_service:latest
    container_name: order_api_container
    restart: unless-stopped
    depends_on:
      order_db:
        condition: service_healthy
      product_service:
        condition: service_started
    environment:
      POSTGRES_HOST: order_db
      POSTGRES_DB: orders
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      ENV: local
      PRODUCT_SERVICE_URL: http://product_service:8000
    volumes:
      - ./backend/order_service/app:/code/app
    ports:
      - "8001:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  # ===== Frontend =====
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: local_frontend:latest
    container_name: product_order_frontend
    restart: unless-stopped
    depends_on:
      product_service:
        condition: service_started
      order_service:
        condition: service_started
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html

volumes:
  product_db_data:
  order_db_data:
